before_script:
  - export DISTRO_CODENAME=`lsb_release -cs` && echo Using distro $DISTRO_CODENAME
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update -yq
  - apt-get install -y lintian
  - rosdep install --from-paths . --ignore-src -r -y
  - export CMAKE_PREFIX_PATH="/opt/ros/$ROS_DISTRO"

variables:
  GET_SOURCES_ATTEMPTS: "3"

#########################
# Templates using anchors
#########################
.amd64_bionic_t: &amd64_bionic_job
  image: ros:dashing-ros-base-bionic
  tags:
    - amd64
    - docker

.armhf_bionic_t: &armhf_bionic_job
  image: ros:dashing-ros-base-bionic
  tags:
    - armhf
    - docker

#############
# Templates
#############
.test:
  stage: test
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - CTEST_OUTPUT_ON_FAILURE=1 make test

# Debian packaging
.package:
  stage: deploy
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX="/opt/ros/$ROS_DISTRO" -DCMAKE_BUILD_TYPE=Release ..
    - make -j 4
    - make package
    - if [ -z "$APT_REPO" ]; then export APT_REPO=testing; fi
    - upload_deb.sh $DISTRO_CODENAME-$APT_REPO *.deb

.package_testing:
  extends: .package
  only:
    - master
  except:
    - tags
  variables:
    TESTING_DEBS: "true"
    APT_REPO: "testing"

.package_stable:
  extends: .package
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+/
  except:
    - branches
  variables:
    APT_REPO: "stable"

##############
#### Jobs ####
##############

# Test (on every commit)
########################
test:bionic:amd64:
  <<: *amd64_bionic_job
  extends: .test

test:bionic:armhf:
  <<: *armhf_bionic_job
  extends: .test

# Deploy testing (only on master)
#################################
package_testing:bionic:amd64:
  <<: *amd64_bionic_job
  extends: .package_testing

package_testing:bionic:armhf:
  <<: *armhf_bionic_job
  extends: .package_testing

# Deploy stable (only for releases, version tags)
#################################################
package_stable:bionic:amd64:
  <<: *amd64_bionic_job
  extends: .package_stable

package_stable:bionic:armhf:
  <<: *armhf_bionic_job
  extends: .package_stable
